
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.UIManager UIManager;

	private global::Gtk.Action FileAction;

	private global::Gtk.Action quitAction;

	private global::Gtk.Action HelpAction;

	private global::Gtk.Action AboutAction;

	private global::Gtk.Action openAction;

	private global::Gtk.Action ClearAction;

	private global::Gtk.VBox vbox1;

	private global::Gtk.MenuBar menubar1;

	private global::Gtk.VPaned vpaned1;

	private global::Gtk.HBox hbox1;

	private global::Gtk.VBox vbox2;

	private global::Gtk.Frame frame2;

	private global::Gtk.Alignment GtkAlignment1;

	private global::Gtk.VBox vbox8;

	private global::Gtk.HBox hbox5;

	private global::Gtk.Button startButton;

	private global::Gtk.Button stopButton;

	private global::Gtk.HBox hbox6;

	private global::Gtk.Button pauseButton;

	private global::Gtk.Button stepButton;

	private global::Gtk.Button resumeButton;

	private global::Gtk.Label GtkLabel7;

	private global::Gtk.Label label29;

	private global::Gtk.HScale threadDelayHScale;

	private global::Gtk.Frame frame5;

	private global::Gtk.Alignment GtkAlignment6;

	private global::Gtk.Table table3;

	private global::Gtk.Label evaluationsLabel;

	private global::Gtk.Label fitnessLabel;

	private global::Gtk.Label generationsLabel;

	private global::Gtk.Label label12;

	private global::Gtk.Label label2;

	private global::Gtk.Label label5;

	private global::Gtk.Label GtkLabel13;

	private global::Gtk.Frame populationFrame;

	private global::Gtk.Alignment GtkAlignment3;

	private global::Gtk.Table table5;

	private global::Gtk.Label chromosomeLengthLabel;

	private global::Gtk.CheckButton evaluateInParallelCheckButton;

	private global::Gtk.Label label21;

	private global::Gtk.Label label24;

	private global::Gtk.CheckButton linearNormalisationCheckButton;

	private global::Gtk.Label populationSizeLabel;

	private global::Gtk.CheckButton reEvaluateCheckbutton;

	private global::Gtk.Label GtkLabel36;

	private global::Gtk.Frame parentSelectionFrame;

	private global::Gtk.Alignment GtkAlignment5;

	private global::Gtk.VBox vbox9;

	private global::Gtk.RadioButton fitnessProportionalRadioButton;

	private global::Gtk.RadioButton stochasticUniversalRadioButton;

	private global::Gtk.RadioButton tournamentRadioButton;

	private global::Gtk.Label GtkLabel35;

	private global::Gtk.HPaned hpaned2;

	private global::Gtk.Notebook mainNotebook;

	private global::Gtk.VBox vbox5;

	private global::Gtk.Frame frame6;

	private global::Gtk.Alignment GtkAlignment8;

	private global::Gtk.VBox vbox4;

	private global::Gtk.Table table1;

	private global::Gtk.Label averageFitnessLabel;

	private global::Gtk.Label duplicateLabel;

	private global::Gtk.Label hammingDistanceLabel;

	private global::Gtk.Label hammingFitnessLabel;

	private global::Gtk.Label label1;

	private global::Gtk.Label label13;

	private global::Gtk.Label label23;

	private global::Gtk.Label label25;

	private global::Gtk.Label label26;

	private global::Gtk.Label label27;

	private global::Gtk.Label label28;

	private global::Gtk.Label maximumFitnessLabel;

	private global::Gtk.Label minimumFitnessLabel;

	private global::Gtk.Label standardDeviationLabel;

	private global::Gtk.CheckButton statisticsCheckButton;

	private global::Gtk.ProgressBar convergenceProgressBar;

	private global::Gtk.ProgressBar diversityProgressBar;

	private global::Gtk.ProgressBar diversityFProgressBar;

	private global::Gtk.ProgressBar convergenceFProgressBar;

	private global::Gtk.ProgressBar duplicateProgressBar;

	private global::Gtk.ProgressBar fitnessProgressBar;

	private global::Gtk.Label GtkLabel31;

	private global::Gtk.Frame frame8;

	private global::Gtk.Alignment GtkAlignment7;

	private global::Gtk.VBox vbox6;

	private global::Gtk.HBox hbox2;

	private global::Gtk.ProgressBar distributionProgressBarZero;

	private global::Gtk.ProgressBar distributionProgressBar1;

	private global::Gtk.ProgressBar distributionProgressBar2;

	private global::Gtk.ProgressBar distributionProgressBar3;

	private global::Gtk.ProgressBar distributionProgressBar4;

	private global::Gtk.ProgressBar distributionProgressBar5;

	private global::Gtk.ProgressBar distributionProgressBar6;

	private global::Gtk.ProgressBar distributionProgressBar7;

	private global::Gtk.ProgressBar distributionProgressBar8;

	private global::Gtk.ProgressBar distributionProgressBar9;

	private global::Gtk.ProgressBar distributionProgressBar10;

	private global::Gtk.ProgressBar distributionProgressBar11;

	private global::Gtk.ProgressBar distributionProgressBar12;

	private global::Gtk.ProgressBar distributionProgressBar13;

	private global::Gtk.ProgressBar distributionProgressBar14;

	private global::Gtk.ProgressBar distributionProgressBar15;

	private global::Gtk.HScale distributionHScale;

	private global::Gtk.Label GtkLabel32;

	private global::Gtk.Label monitorTabLabel;

	private global::Gtk.ScrolledWindow populationScrolledWindow;

	private global::Gtk.Label genoTypicTabLabel;

	private global::Gtk.ScrolledWindow GtkScrolledWindow8;

	private global::Gtk.TextView sourceCodeTextView;

	private global::Gtk.Label sourceCodeTabLabel;

	private global::Gtk.Notebook notebook5;

	private global::Gtk.VBox vbox3;

	private global::Gtk.HBox hbox9;

	private global::Gtk.CheckButton crossoverEnabledCheckButton;

	private global::Gtk.CheckButton crossoverAllowDuplicatesCheckButton;

	private global::Gtk.Label label3;

	private global::Gtk.HScale crossoverProbabilityHScale;

	private global::Gtk.HBox hbox8;

	private global::Gtk.Frame frame4;

	private global::Gtk.Alignment GtkAlignment;

	private global::Gtk.VBox vbox10;

	private global::Gtk.RadioButton crossoverTypeSingleRadioButton;

	private global::Gtk.RadioButton crossoverTypeDoubleRadioButton;

	private global::Gtk.RadioButton crossoverTypeDoubleOrderedRadioButton;

	private global::Gtk.Label GtkLabel22;

	private global::Gtk.Frame frame7;

	private global::Gtk.Alignment GtkAlignment2;

	private global::Gtk.VBox vbox11;

	private global::Gtk.RadioButton crossoverReplacementGenerational;

	private global::Gtk.RadioButton crossoverReplacementDeleteLast;

	private global::Gtk.Label GtkLabel25;

	private global::Gtk.ScrolledWindow GtkScrolledWindow;

	private global::Gtk.TextView crossoverTextView;

	private global::Gtk.Label label7;

	private global::Gtk.VBox vbox12;

	private global::Gtk.HBox hbox7;

	private global::Gtk.CheckButton binaryMutateEnabledCheckButton;

	private global::Gtk.CheckButton binaryMutateAllowDuplicatesCheckButton;

	private global::Gtk.Label label4;

	private global::Gtk.HScale binaryMutateProbabilityHScale;

	private global::Gtk.ScrolledWindow GtkScrolledWindow1;

	private global::Gtk.TextView binaryMutateTextView;

	private global::Gtk.Label label9;

	private global::Gtk.VBox vbox13;

	private global::Gtk.CheckButton eliteEnabledCheckButton;

	private global::Gtk.Label label8;

	private global::Gtk.HScale elitePercentageHScale;

	private global::Gtk.ScrolledWindow GtkScrolledWindow3;

	private global::Gtk.TextView eliteTextView;

	private global::Gtk.Label label10;

	private global::Gtk.VBox vbox15;

	private global::Gtk.HBox hbox10;

	private global::Gtk.CheckButton randomReplaceEnabledCheckButton;

	private global::Gtk.CheckButton randomReplaceAllowDuplicatesCheckButton;

	private global::Gtk.Label label18;

	private global::Gtk.HScale randomReplacePercentageHScale;

	private global::Gtk.ScrolledWindow GtkScrolledWindow5;

	private global::Gtk.TextView randomReplaceTextView;

	private global::Gtk.Label label14;

	private global::Gtk.VBox vbox16;

	private global::Gtk.CheckButton swapMutateEnabledCheckButton;

	private global::Gtk.Label label19;

	private global::Gtk.HScale swapMutateProbabilityHScale;

	private global::Gtk.ScrolledWindow GtkScrolledWindow6;

	private global::Gtk.TextView swapMutateTextView;

	private global::Gtk.Label label15;

	private global::Gtk.VBox vbox17;

	private global::Gtk.CheckButton memoryEnabledCheckButton;

	private global::Gtk.Label label20;

	private global::Gtk.HScale memorySizeHScale;

	private global::Gtk.Label label22;

	private global::Gtk.HScale memoryUpdateHScale;

	private global::Gtk.ScrolledWindow GtkScrolledWindow7;

	private global::Gtk.TextView memoryTextView;

	private global::Gtk.Label label16;

	private global::Gtk.Notebook notebook1;

	private global::Gtk.ScrolledWindow scrolledwindow1;

	private global::Gtk.VBox vbox7;

	private global::Gtk.ScrolledWindow GtkScrolledWindow2;

	private global::Gtk.TextView outputTextView;

	private global::Gtk.Toolbar toolbar1;

	private global::Gtk.Label label6;

	private global::Gtk.Statusbar statusBar;

	private global::Gtk.Label label31;

	private global::Gtk.Label elapsedGenTimeLabel;

	private global::Gtk.Label label17;

	private global::Gtk.Label elapsedTimeLabel;

	protected virtual void Build ()
	{
		global::Stetic.Gui.Initialize (this);
		// Widget MainWindow
		this.UIManager = new global::Gtk.UIManager ();
		global::Gtk.ActionGroup w1 = new global::Gtk.ActionGroup ("Default");
		this.FileAction = new global::Gtk.Action ("FileAction", global::Mono.Unix.Catalog.GetString ("File"), null, null);
		this.FileAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("File");
		w1.Add (this.FileAction, "function");
		this.quitAction = new global::Gtk.Action ("quitAction", global::Mono.Unix.Catalog.GetString ("_Quit"), null, "gtk-quit");
		this.quitAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Quit");
		w1.Add (this.quitAction, "<Control>x");
		this.HelpAction = new global::Gtk.Action ("HelpAction", global::Mono.Unix.Catalog.GetString ("Help"), null, null);
		this.HelpAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Help");
		w1.Add (this.HelpAction, null);
		this.AboutAction = new global::Gtk.Action ("AboutAction", global::Mono.Unix.Catalog.GetString ("About"), null, null);
		this.AboutAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("About");
		w1.Add (this.AboutAction, null);
		this.openAction = new global::Gtk.Action ("openAction", global::Mono.Unix.Catalog.GetString ("Open Consumer Functions Assembly"), null, "gtk-open");
		this.openAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Open Fitness Function");
		w1.Add (this.openAction, null);
		this.ClearAction = new global::Gtk.Action ("ClearAction", global::Mono.Unix.Catalog.GetString ("Clear"), null, null);
		this.ClearAction.ShortLabel = global::Mono.Unix.Catalog.GetString ("Clear");
		w1.Add (this.ClearAction, null);
		this.UIManager.InsertActionGroup (w1, 0);
		this.AddAccelGroup (this.UIManager.AccelGroup);
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString ("GAF Lab");
		this.Icon = new global::Gdk.Pixbuf (global::System.IO.Path.Combine (global::System.AppDomain.CurrentDomain.BaseDirectory, "./GAF128.ico"));
		this.WindowPosition = ((global::Gtk.WindowPosition)(3));
		this.BorderWidth = ((uint)(10));
		this.DefaultWidth = 1280;
		this.DefaultHeight = 760;
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox1 = new global::Gtk.VBox ();
		this.vbox1.Name = "vbox1";
		this.vbox1.Spacing = 6;
		// Container child vbox1.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><menubar name='menubar1'><menu name='FileAction' action='FileAction'><menuitem name='openAction' action='openAction'/><menuitem name='quitAction' action='quitAction'/></menu><menu name='HelpAction' action='HelpAction'><menuitem name='AboutAction' action='AboutAction'/></menu></menubar></ui>");
		this.menubar1 = ((global::Gtk.MenuBar)(this.UIManager.GetWidget ("/menubar1")));
		this.menubar1.Name = "menubar1";
		this.vbox1.Add (this.menubar1);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.menubar1]));
		w2.Position = 0;
		w2.Expand = false;
		w2.Fill = false;
		// Container child vbox1.Gtk.Box+BoxChild
		this.vpaned1 = new global::Gtk.VPaned ();
		this.vpaned1.CanFocus = true;
		this.vpaned1.Name = "vpaned1";
		this.vpaned1.Position = 519;
		this.vpaned1.BorderWidth = ((uint)(1));
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.hbox1 = new global::Gtk.HBox ();
		this.hbox1.Name = "hbox1";
		this.hbox1.Spacing = 6;
		// Container child hbox1.Gtk.Box+BoxChild
		this.vbox2 = new global::Gtk.VBox ();
		this.vbox2.Name = "vbox2";
		this.vbox2.Spacing = 6;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame2 = new global::Gtk.Frame ();
		this.frame2.Name = "frame2";
		this.frame2.BorderWidth = ((uint)(1));
		// Container child frame2.Gtk.Container+ContainerChild
		this.GtkAlignment1 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment1.Name = "GtkAlignment1";
		this.GtkAlignment1.LeftPadding = ((uint)(12));
		this.GtkAlignment1.BorderWidth = ((uint)(5));
		// Container child GtkAlignment1.Gtk.Container+ContainerChild
		this.vbox8 = new global::Gtk.VBox ();
		this.vbox8.Name = "vbox8";
		this.vbox8.Spacing = 6;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox5 = new global::Gtk.HBox ();
		this.hbox5.Name = "hbox5";
		this.hbox5.Spacing = 6;
		// Container child hbox5.Gtk.Box+BoxChild
		this.startButton = new global::Gtk.Button ();
		this.startButton.CanFocus = true;
		this.startButton.Name = "startButton";
		this.startButton.UseUnderline = true;
		this.startButton.Label = global::Mono.Unix.Catalog.GetString ("Start");
		this.hbox5.Add (this.startButton);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.startButton]));
		w3.Position = 0;
		// Container child hbox5.Gtk.Box+BoxChild
		this.stopButton = new global::Gtk.Button ();
		this.stopButton.CanFocus = true;
		this.stopButton.Name = "stopButton";
		this.stopButton.UseUnderline = true;
		this.stopButton.Label = global::Mono.Unix.Catalog.GetString ("Stop");
		this.hbox5.Add (this.stopButton);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5 [this.stopButton]));
		w4.Position = 1;
		this.vbox8.Add (this.hbox5);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox5]));
		w5.Position = 0;
		// Container child vbox8.Gtk.Box+BoxChild
		this.hbox6 = new global::Gtk.HBox ();
		this.hbox6.Name = "hbox6";
		this.hbox6.Homogeneous = true;
		this.hbox6.Spacing = 6;
		// Container child hbox6.Gtk.Box+BoxChild
		this.pauseButton = new global::Gtk.Button ();
		this.pauseButton.CanFocus = true;
		this.pauseButton.Name = "pauseButton";
		this.pauseButton.UseUnderline = true;
		this.pauseButton.Label = global::Mono.Unix.Catalog.GetString ("Pause");
		this.hbox6.Add (this.pauseButton);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.pauseButton]));
		w6.Position = 0;
		// Container child hbox6.Gtk.Box+BoxChild
		this.stepButton = new global::Gtk.Button ();
		this.stepButton.CanFocus = true;
		this.stepButton.Name = "stepButton";
		this.stepButton.UseUnderline = true;
		this.stepButton.Label = global::Mono.Unix.Catalog.GetString ("Step");
		this.hbox6.Add (this.stepButton);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.stepButton]));
		w7.Position = 1;
		// Container child hbox6.Gtk.Box+BoxChild
		this.resumeButton = new global::Gtk.Button ();
		this.resumeButton.CanFocus = true;
		this.resumeButton.Name = "resumeButton";
		this.resumeButton.UseUnderline = true;
		this.resumeButton.Label = global::Mono.Unix.Catalog.GetString ("Resume");
		this.hbox6.Add (this.resumeButton);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox6 [this.resumeButton]));
		w8.Position = 2;
		this.vbox8.Add (this.hbox6);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox8 [this.hbox6]));
		w9.Position = 1;
		w9.Expand = false;
		w9.Fill = false;
		this.GtkAlignment1.Add (this.vbox8);
		this.frame2.Add (this.GtkAlignment1);
		this.GtkLabel7 = new global::Gtk.Label ();
		this.GtkLabel7.Name = "GtkLabel7";
		this.GtkLabel7.LabelProp = global::Mono.Unix.Catalog.GetString ("Start/Stop");
		this.GtkLabel7.UseMarkup = true;
		this.frame2.LabelWidget = this.GtkLabel7;
		this.vbox2.Add (this.frame2);
		global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame2]));
		w12.Position = 0;
		w12.Expand = false;
		w12.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.label29 = new global::Gtk.Label ();
		this.label29.Name = "label29";
		this.label29.LabelProp = global::Mono.Unix.Catalog.GetString ("Delay (ms/gen)");
		this.vbox2.Add (this.label29);
		global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.label29]));
		w13.Position = 1;
		w13.Expand = false;
		w13.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.threadDelayHScale = new global::Gtk.HScale (null);
		this.threadDelayHScale.CanFocus = true;
		this.threadDelayHScale.Name = "threadDelayHScale";
		this.threadDelayHScale.Adjustment.Upper = 1000;
		this.threadDelayHScale.Adjustment.PageIncrement = 10;
		this.threadDelayHScale.Adjustment.StepIncrement = 1;
		this.threadDelayHScale.DrawValue = true;
		this.threadDelayHScale.Digits = 0;
		this.threadDelayHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox2.Add (this.threadDelayHScale);
		global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.threadDelayHScale]));
		w14.Position = 2;
		w14.Expand = false;
		w14.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.frame5 = new global::Gtk.Frame ();
		this.frame5.Name = "frame5";
		this.frame5.BorderWidth = ((uint)(1));
		// Container child frame5.Gtk.Container+ContainerChild
		this.GtkAlignment6 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment6.Name = "GtkAlignment6";
		this.GtkAlignment6.LeftPadding = ((uint)(12));
		this.GtkAlignment6.BorderWidth = ((uint)(5));
		// Container child GtkAlignment6.Gtk.Container+ContainerChild
		this.table3 = new global::Gtk.Table (((uint)(3)), ((uint)(2)), false);
		this.table3.Name = "table3";
		this.table3.RowSpacing = ((uint)(6));
		this.table3.ColumnSpacing = ((uint)(6));
		// Container child table3.Gtk.Table+TableChild
		this.evaluationsLabel = new global::Gtk.Label ();
		this.evaluationsLabel.Name = "evaluationsLabel";
		this.evaluationsLabel.Xalign = 1F;
		this.evaluationsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.evaluationsLabel);
		global::Gtk.Table.TableChild w15 = ((global::Gtk.Table.TableChild)(this.table3 [this.evaluationsLabel]));
		w15.TopAttach = ((uint)(1));
		w15.BottomAttach = ((uint)(2));
		w15.LeftAttach = ((uint)(1));
		w15.RightAttach = ((uint)(2));
		w15.XOptions = ((global::Gtk.AttachOptions)(4));
		w15.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.fitnessLabel = new global::Gtk.Label ();
		this.fitnessLabel.Name = "fitnessLabel";
		this.fitnessLabel.Xalign = 1F;
		this.fitnessLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.fitnessLabel);
		global::Gtk.Table.TableChild w16 = ((global::Gtk.Table.TableChild)(this.table3 [this.fitnessLabel]));
		w16.TopAttach = ((uint)(2));
		w16.BottomAttach = ((uint)(3));
		w16.LeftAttach = ((uint)(1));
		w16.RightAttach = ((uint)(2));
		w16.XOptions = ((global::Gtk.AttachOptions)(4));
		w16.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.generationsLabel = new global::Gtk.Label ();
		this.generationsLabel.Name = "generationsLabel";
		this.generationsLabel.Xalign = 1F;
		this.generationsLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table3.Add (this.generationsLabel);
		global::Gtk.Table.TableChild w17 = ((global::Gtk.Table.TableChild)(this.table3 [this.generationsLabel]));
		w17.LeftAttach = ((uint)(1));
		w17.RightAttach = ((uint)(2));
		w17.XOptions = ((global::Gtk.AttachOptions)(4));
		w17.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label12 = new global::Gtk.Label ();
		this.label12.Name = "label12";
		this.label12.Xalign = 0F;
		this.label12.LabelProp = global::Mono.Unix.Catalog.GetString ("Max Fitness");
		this.table3.Add (this.label12);
		global::Gtk.Table.TableChild w18 = ((global::Gtk.Table.TableChild)(this.table3 [this.label12]));
		w18.TopAttach = ((uint)(2));
		w18.BottomAttach = ((uint)(3));
		w18.XOptions = ((global::Gtk.AttachOptions)(4));
		w18.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label2 = new global::Gtk.Label ();
		this.label2.Name = "label2";
		this.label2.Xalign = 0F;
		this.label2.LabelProp = global::Mono.Unix.Catalog.GetString ("Generation");
		this.table3.Add (this.label2);
		global::Gtk.Table.TableChild w19 = ((global::Gtk.Table.TableChild)(this.table3 [this.label2]));
		w19.XOptions = ((global::Gtk.AttachOptions)(4));
		w19.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table3.Gtk.Table+TableChild
		this.label5 = new global::Gtk.Label ();
		this.label5.Name = "label5";
		this.label5.Xalign = 0F;
		this.label5.LabelProp = global::Mono.Unix.Catalog.GetString ("Evaluations");
		this.table3.Add (this.label5);
		global::Gtk.Table.TableChild w20 = ((global::Gtk.Table.TableChild)(this.table3 [this.label5]));
		w20.TopAttach = ((uint)(1));
		w20.BottomAttach = ((uint)(2));
		w20.XOptions = ((global::Gtk.AttachOptions)(4));
		w20.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment6.Add (this.table3);
		this.frame5.Add (this.GtkAlignment6);
		this.GtkLabel13 = new global::Gtk.Label ();
		this.GtkLabel13.Name = "GtkLabel13";
		this.GtkLabel13.LabelProp = global::Mono.Unix.Catalog.GetString ("Status");
		this.GtkLabel13.UseMarkup = true;
		this.frame5.LabelWidget = this.GtkLabel13;
		this.vbox2.Add (this.frame5);
		global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.frame5]));
		w23.Position = 3;
		w23.Expand = false;
		w23.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.populationFrame = new global::Gtk.Frame ();
		this.populationFrame.Name = "populationFrame";
		this.populationFrame.BorderWidth = ((uint)(1));
		// Container child populationFrame.Gtk.Container+ContainerChild
		this.GtkAlignment3 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment3.Name = "GtkAlignment3";
		this.GtkAlignment3.LeftPadding = ((uint)(12));
		this.GtkAlignment3.BorderWidth = ((uint)(5));
		// Container child GtkAlignment3.Gtk.Container+ContainerChild
		this.table5 = new global::Gtk.Table (((uint)(5)), ((uint)(2)), false);
		this.table5.Name = "table5";
		this.table5.RowSpacing = ((uint)(6));
		this.table5.ColumnSpacing = ((uint)(6));
		// Container child table5.Gtk.Table+TableChild
		this.chromosomeLengthLabel = new global::Gtk.Label ();
		this.chromosomeLengthLabel.Name = "chromosomeLengthLabel";
		this.chromosomeLengthLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table5.Add (this.chromosomeLengthLabel);
		global::Gtk.Table.TableChild w24 = ((global::Gtk.Table.TableChild)(this.table5 [this.chromosomeLengthLabel]));
		w24.TopAttach = ((uint)(1));
		w24.BottomAttach = ((uint)(2));
		w24.LeftAttach = ((uint)(1));
		w24.RightAttach = ((uint)(2));
		w24.XOptions = ((global::Gtk.AttachOptions)(4));
		w24.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.evaluateInParallelCheckButton = new global::Gtk.CheckButton ();
		this.evaluateInParallelCheckButton.CanFocus = true;
		this.evaluateInParallelCheckButton.Name = "evaluateInParallelCheckButton";
		this.evaluateInParallelCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Evaluate in Parallel");
		this.evaluateInParallelCheckButton.DrawIndicator = true;
		this.evaluateInParallelCheckButton.UseUnderline = true;
		this.table5.Add (this.evaluateInParallelCheckButton);
		global::Gtk.Table.TableChild w25 = ((global::Gtk.Table.TableChild)(this.table5 [this.evaluateInParallelCheckButton]));
		w25.TopAttach = ((uint)(4));
		w25.BottomAttach = ((uint)(5));
		w25.XOptions = ((global::Gtk.AttachOptions)(4));
		w25.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label21 = new global::Gtk.Label ();
		this.label21.Name = "label21";
		this.label21.Xalign = 0F;
		this.label21.Yalign = 0F;
		this.label21.LabelProp = global::Mono.Unix.Catalog.GetString ("Chromosome Length");
		this.table5.Add (this.label21);
		global::Gtk.Table.TableChild w26 = ((global::Gtk.Table.TableChild)(this.table5 [this.label21]));
		w26.TopAttach = ((uint)(1));
		w26.BottomAttach = ((uint)(2));
		w26.XOptions = ((global::Gtk.AttachOptions)(4));
		w26.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.label24 = new global::Gtk.Label ();
		this.label24.Name = "label24";
		this.label24.Xalign = 0F;
		this.label24.Yalign = 0F;
		this.label24.LabelProp = global::Mono.Unix.Catalog.GetString ("Population Size");
		this.table5.Add (this.label24);
		global::Gtk.Table.TableChild w27 = ((global::Gtk.Table.TableChild)(this.table5 [this.label24]));
		w27.RightAttach = ((uint)(2));
		w27.XOptions = ((global::Gtk.AttachOptions)(4));
		w27.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.linearNormalisationCheckButton = new global::Gtk.CheckButton ();
		this.linearNormalisationCheckButton.CanFocus = true;
		this.linearNormalisationCheckButton.Name = "linearNormalisationCheckButton";
		this.linearNormalisationCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Linear Normalisation");
		this.linearNormalisationCheckButton.Active = true;
		this.linearNormalisationCheckButton.DrawIndicator = true;
		this.linearNormalisationCheckButton.UseUnderline = true;
		this.table5.Add (this.linearNormalisationCheckButton);
		global::Gtk.Table.TableChild w28 = ((global::Gtk.Table.TableChild)(this.table5 [this.linearNormalisationCheckButton]));
		w28.TopAttach = ((uint)(3));
		w28.BottomAttach = ((uint)(4));
		w28.XOptions = ((global::Gtk.AttachOptions)(4));
		w28.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.populationSizeLabel = new global::Gtk.Label ();
		this.populationSizeLabel.Name = "populationSizeLabel";
		this.populationSizeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table5.Add (this.populationSizeLabel);
		global::Gtk.Table.TableChild w29 = ((global::Gtk.Table.TableChild)(this.table5 [this.populationSizeLabel]));
		w29.LeftAttach = ((uint)(1));
		w29.RightAttach = ((uint)(2));
		w29.XOptions = ((global::Gtk.AttachOptions)(4));
		w29.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table5.Gtk.Table+TableChild
		this.reEvaluateCheckbutton = new global::Gtk.CheckButton ();
		this.reEvaluateCheckbutton.CanFocus = true;
		this.reEvaluateCheckbutton.Name = "reEvaluateCheckbutton";
		this.reEvaluateCheckbutton.Label = global::Mono.Unix.Catalog.GetString ("Re Evaluate All");
		this.reEvaluateCheckbutton.DrawIndicator = true;
		this.reEvaluateCheckbutton.UseUnderline = true;
		this.table5.Add (this.reEvaluateCheckbutton);
		global::Gtk.Table.TableChild w30 = ((global::Gtk.Table.TableChild)(this.table5 [this.reEvaluateCheckbutton]));
		w30.TopAttach = ((uint)(2));
		w30.BottomAttach = ((uint)(3));
		w30.XOptions = ((global::Gtk.AttachOptions)(4));
		w30.YOptions = ((global::Gtk.AttachOptions)(4));
		this.GtkAlignment3.Add (this.table5);
		this.populationFrame.Add (this.GtkAlignment3);
		this.GtkLabel36 = new global::Gtk.Label ();
		this.GtkLabel36.Name = "GtkLabel36";
		this.GtkLabel36.LabelProp = global::Mono.Unix.Catalog.GetString ("Population");
		this.GtkLabel36.UseMarkup = true;
		this.populationFrame.LabelWidget = this.GtkLabel36;
		this.vbox2.Add (this.populationFrame);
		global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.populationFrame]));
		w33.Position = 4;
		w33.Expand = false;
		w33.Fill = false;
		// Container child vbox2.Gtk.Box+BoxChild
		this.parentSelectionFrame = new global::Gtk.Frame ();
		this.parentSelectionFrame.Name = "parentSelectionFrame";
		this.parentSelectionFrame.BorderWidth = ((uint)(1));
		// Container child parentSelectionFrame.Gtk.Container+ContainerChild
		this.GtkAlignment5 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment5.Name = "GtkAlignment5";
		this.GtkAlignment5.LeftPadding = ((uint)(12));
		this.GtkAlignment5.BorderWidth = ((uint)(5));
		// Container child GtkAlignment5.Gtk.Container+ContainerChild
		this.vbox9 = new global::Gtk.VBox ();
		this.vbox9.Name = "vbox9";
		this.vbox9.Spacing = 6;
		// Container child vbox9.Gtk.Box+BoxChild
		this.fitnessProportionalRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Fitness Proportional"));
		this.fitnessProportionalRadioButton.CanFocus = true;
		this.fitnessProportionalRadioButton.Name = "fitnessProportionalRadioButton";
		this.fitnessProportionalRadioButton.DrawIndicator = true;
		this.fitnessProportionalRadioButton.UseUnderline = true;
		this.fitnessProportionalRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox9.Add (this.fitnessProportionalRadioButton);
		global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.fitnessProportionalRadioButton]));
		w34.Position = 0;
		w34.Expand = false;
		w34.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.stochasticUniversalRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Stochastic Universal"));
		this.stochasticUniversalRadioButton.CanFocus = true;
		this.stochasticUniversalRadioButton.Name = "stochasticUniversalRadioButton";
		this.stochasticUniversalRadioButton.DrawIndicator = true;
		this.stochasticUniversalRadioButton.UseUnderline = true;
		this.stochasticUniversalRadioButton.Group = this.fitnessProportionalRadioButton.Group;
		this.vbox9.Add (this.stochasticUniversalRadioButton);
		global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.stochasticUniversalRadioButton]));
		w35.Position = 1;
		w35.Expand = false;
		w35.Fill = false;
		// Container child vbox9.Gtk.Box+BoxChild
		this.tournamentRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Tournament"));
		this.tournamentRadioButton.CanFocus = true;
		this.tournamentRadioButton.Name = "tournamentRadioButton";
		this.tournamentRadioButton.DrawIndicator = true;
		this.tournamentRadioButton.UseUnderline = true;
		this.tournamentRadioButton.Group = this.fitnessProportionalRadioButton.Group;
		this.vbox9.Add (this.tournamentRadioButton);
		global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.vbox9 [this.tournamentRadioButton]));
		w36.Position = 2;
		w36.Expand = false;
		w36.Fill = false;
		this.GtkAlignment5.Add (this.vbox9);
		this.parentSelectionFrame.Add (this.GtkAlignment5);
		this.GtkLabel35 = new global::Gtk.Label ();
		this.GtkLabel35.Name = "GtkLabel35";
		this.GtkLabel35.LabelProp = global::Mono.Unix.Catalog.GetString ("Parent Selection");
		this.GtkLabel35.UseMarkup = true;
		this.parentSelectionFrame.LabelWidget = this.GtkLabel35;
		this.vbox2.Add (this.parentSelectionFrame);
		global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.parentSelectionFrame]));
		w39.Position = 5;
		w39.Expand = false;
		w39.Fill = false;
		this.hbox1.Add (this.vbox2);
		global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.vbox2]));
		w40.Position = 0;
		w40.Expand = false;
		w40.Fill = false;
		// Container child hbox1.Gtk.Box+BoxChild
		this.hpaned2 = new global::Gtk.HPaned ();
		this.hpaned2.CanFocus = true;
		this.hpaned2.Name = "hpaned2";
		this.hpaned2.Position = 490;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.mainNotebook = new global::Gtk.Notebook ();
		this.mainNotebook.CanFocus = true;
		this.mainNotebook.Name = "mainNotebook";
		this.mainNotebook.CurrentPage = 0;
		// Container child mainNotebook.Gtk.Notebook+NotebookChild
		this.vbox5 = new global::Gtk.VBox ();
		this.vbox5.Name = "vbox5";
		this.vbox5.Spacing = 6;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame6 = new global::Gtk.Frame ();
		this.frame6.Name = "frame6";
		// Container child frame6.Gtk.Container+ContainerChild
		this.GtkAlignment8 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment8.Name = "GtkAlignment8";
		this.GtkAlignment8.LeftPadding = ((uint)(12));
		this.GtkAlignment8.BorderWidth = ((uint)(5));
		// Container child GtkAlignment8.Gtk.Container+ContainerChild
		this.vbox4 = new global::Gtk.VBox ();
		this.vbox4.Name = "vbox4";
		this.vbox4.Spacing = 6;
		// Container child vbox4.Gtk.Box+BoxChild
		this.table1 = new global::Gtk.Table (((uint)(8)), ((uint)(2)), false);
		this.table1.Name = "table1";
		this.table1.RowSpacing = ((uint)(6));
		this.table1.ColumnSpacing = ((uint)(6));
		// Container child table1.Gtk.Table+TableChild
		this.averageFitnessLabel = new global::Gtk.Label ();
		this.averageFitnessLabel.Name = "averageFitnessLabel";
		this.averageFitnessLabel.Xalign = 0F;
		this.averageFitnessLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.averageFitnessLabel);
		global::Gtk.Table.TableChild w41 = ((global::Gtk.Table.TableChild)(this.table1 [this.averageFitnessLabel]));
		w41.TopAttach = ((uint)(3));
		w41.BottomAttach = ((uint)(4));
		w41.LeftAttach = ((uint)(1));
		w41.RightAttach = ((uint)(2));
		w41.XOptions = ((global::Gtk.AttachOptions)(4));
		w41.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.duplicateLabel = new global::Gtk.Label ();
		this.duplicateLabel.Name = "duplicateLabel";
		this.duplicateLabel.Xalign = 0F;
		this.duplicateLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.duplicateLabel);
		global::Gtk.Table.TableChild w42 = ((global::Gtk.Table.TableChild)(this.table1 [this.duplicateLabel]));
		w42.TopAttach = ((uint)(7));
		w42.BottomAttach = ((uint)(8));
		w42.LeftAttach = ((uint)(1));
		w42.RightAttach = ((uint)(2));
		w42.XOptions = ((global::Gtk.AttachOptions)(4));
		w42.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hammingDistanceLabel = new global::Gtk.Label ();
		this.hammingDistanceLabel.Name = "hammingDistanceLabel";
		this.hammingDistanceLabel.Xalign = 0F;
		this.hammingDistanceLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.hammingDistanceLabel);
		global::Gtk.Table.TableChild w43 = ((global::Gtk.Table.TableChild)(this.table1 [this.hammingDistanceLabel]));
		w43.TopAttach = ((uint)(1));
		w43.BottomAttach = ((uint)(2));
		w43.LeftAttach = ((uint)(1));
		w43.RightAttach = ((uint)(2));
		w43.XOptions = ((global::Gtk.AttachOptions)(4));
		w43.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.hammingFitnessLabel = new global::Gtk.Label ();
		this.hammingFitnessLabel.Name = "hammingFitnessLabel";
		this.hammingFitnessLabel.Xalign = 0F;
		this.hammingFitnessLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.hammingFitnessLabel);
		global::Gtk.Table.TableChild w44 = ((global::Gtk.Table.TableChild)(this.table1 [this.hammingFitnessLabel]));
		w44.TopAttach = ((uint)(2));
		w44.BottomAttach = ((uint)(3));
		w44.LeftAttach = ((uint)(1));
		w44.RightAttach = ((uint)(2));
		w44.XOptions = ((global::Gtk.AttachOptions)(4));
		w44.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label1 = new global::Gtk.Label ();
		this.label1.Name = "label1";
		this.label1.Xalign = 0F;
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString ("Duplicates (count)");
		this.table1.Add (this.label1);
		global::Gtk.Table.TableChild w45 = ((global::Gtk.Table.TableChild)(this.table1 [this.label1]));
		w45.TopAttach = ((uint)(7));
		w45.BottomAttach = ((uint)(8));
		w45.XOptions = ((global::Gtk.AttachOptions)(4));
		w45.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label13 = new global::Gtk.Label ();
		this.label13.Name = "label13";
		this.label13.Xalign = 0F;
		this.label13.LabelProp = global::Mono.Unix.Catalog.GetString ("Average Fitness Distance");
		this.table1.Add (this.label13);
		global::Gtk.Table.TableChild w46 = ((global::Gtk.Table.TableChild)(this.table1 [this.label13]));
		w46.TopAttach = ((uint)(2));
		w46.BottomAttach = ((uint)(3));
		w46.XOptions = ((global::Gtk.AttachOptions)(4));
		w46.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label23 = new global::Gtk.Label ();
		this.label23.Name = "label23";
		this.label23.Xalign = 0F;
		this.label23.LabelProp = global::Mono.Unix.Catalog.GetString ("Average Hamming Distance");
		this.table1.Add (this.label23);
		global::Gtk.Table.TableChild w47 = ((global::Gtk.Table.TableChild)(this.table1 [this.label23]));
		w47.TopAttach = ((uint)(1));
		w47.BottomAttach = ((uint)(2));
		w47.XOptions = ((global::Gtk.AttachOptions)(4));
		w47.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label25 = new global::Gtk.Label ();
		this.label25.Name = "label25";
		this.label25.Xalign = 0F;
		this.label25.LabelProp = global::Mono.Unix.Catalog.GetString ("Average Fitness");
		this.table1.Add (this.label25);
		global::Gtk.Table.TableChild w48 = ((global::Gtk.Table.TableChild)(this.table1 [this.label25]));
		w48.TopAttach = ((uint)(3));
		w48.BottomAttach = ((uint)(4));
		w48.XOptions = ((global::Gtk.AttachOptions)(4));
		w48.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label26 = new global::Gtk.Label ();
		this.label26.Name = "label26";
		this.label26.Xalign = 0F;
		this.label26.LabelProp = global::Mono.Unix.Catalog.GetString ("Maximum Fitness");
		this.table1.Add (this.label26);
		global::Gtk.Table.TableChild w49 = ((global::Gtk.Table.TableChild)(this.table1 [this.label26]));
		w49.TopAttach = ((uint)(4));
		w49.BottomAttach = ((uint)(5));
		w49.XOptions = ((global::Gtk.AttachOptions)(4));
		w49.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label27 = new global::Gtk.Label ();
		this.label27.Name = "label27";
		this.label27.Xalign = 0F;
		this.label27.LabelProp = global::Mono.Unix.Catalog.GetString ("Minimum Fitness");
		this.table1.Add (this.label27);
		global::Gtk.Table.TableChild w50 = ((global::Gtk.Table.TableChild)(this.table1 [this.label27]));
		w50.TopAttach = ((uint)(5));
		w50.BottomAttach = ((uint)(6));
		w50.XOptions = ((global::Gtk.AttachOptions)(4));
		w50.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.label28 = new global::Gtk.Label ();
		this.label28.Name = "label28";
		this.label28.Xalign = 0F;
		this.label28.LabelProp = global::Mono.Unix.Catalog.GetString ("Fitness Standard Deviation");
		this.table1.Add (this.label28);
		global::Gtk.Table.TableChild w51 = ((global::Gtk.Table.TableChild)(this.table1 [this.label28]));
		w51.TopAttach = ((uint)(6));
		w51.BottomAttach = ((uint)(7));
		w51.XOptions = ((global::Gtk.AttachOptions)(4));
		w51.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.maximumFitnessLabel = new global::Gtk.Label ();
		this.maximumFitnessLabel.Name = "maximumFitnessLabel";
		this.maximumFitnessLabel.Xalign = 0F;
		this.maximumFitnessLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.maximumFitnessLabel);
		global::Gtk.Table.TableChild w52 = ((global::Gtk.Table.TableChild)(this.table1 [this.maximumFitnessLabel]));
		w52.TopAttach = ((uint)(4));
		w52.BottomAttach = ((uint)(5));
		w52.LeftAttach = ((uint)(1));
		w52.RightAttach = ((uint)(2));
		w52.XOptions = ((global::Gtk.AttachOptions)(4));
		w52.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.minimumFitnessLabel = new global::Gtk.Label ();
		this.minimumFitnessLabel.Name = "minimumFitnessLabel";
		this.minimumFitnessLabel.Xalign = 0F;
		this.minimumFitnessLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.minimumFitnessLabel);
		global::Gtk.Table.TableChild w53 = ((global::Gtk.Table.TableChild)(this.table1 [this.minimumFitnessLabel]));
		w53.TopAttach = ((uint)(5));
		w53.BottomAttach = ((uint)(6));
		w53.LeftAttach = ((uint)(1));
		w53.RightAttach = ((uint)(2));
		w53.XOptions = ((global::Gtk.AttachOptions)(4));
		w53.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.standardDeviationLabel = new global::Gtk.Label ();
		this.standardDeviationLabel.Name = "standardDeviationLabel";
		this.standardDeviationLabel.Xalign = 0F;
		this.standardDeviationLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.table1.Add (this.standardDeviationLabel);
		global::Gtk.Table.TableChild w54 = ((global::Gtk.Table.TableChild)(this.table1 [this.standardDeviationLabel]));
		w54.TopAttach = ((uint)(6));
		w54.BottomAttach = ((uint)(7));
		w54.LeftAttach = ((uint)(1));
		w54.RightAttach = ((uint)(2));
		w54.XOptions = ((global::Gtk.AttachOptions)(4));
		w54.YOptions = ((global::Gtk.AttachOptions)(4));
		// Container child table1.Gtk.Table+TableChild
		this.statisticsCheckButton = new global::Gtk.CheckButton ();
		this.statisticsCheckButton.CanFocus = true;
		this.statisticsCheckButton.Name = "statisticsCheckButton";
		this.statisticsCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.statisticsCheckButton.DrawIndicator = true;
		this.statisticsCheckButton.UseUnderline = true;
		this.table1.Add (this.statisticsCheckButton);
		global::Gtk.Table.TableChild w55 = ((global::Gtk.Table.TableChild)(this.table1 [this.statisticsCheckButton]));
		w55.XOptions = ((global::Gtk.AttachOptions)(4));
		w55.YOptions = ((global::Gtk.AttachOptions)(4));
		this.vbox4.Add (this.table1);
		global::Gtk.Box.BoxChild w56 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.table1]));
		w56.Position = 0;
		w56.Expand = false;
		w56.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.convergenceProgressBar = new global::Gtk.ProgressBar ();
		this.convergenceProgressBar.Name = "convergenceProgressBar";
		this.convergenceProgressBar.Text = global::Mono.Unix.Catalog.GetString ("Convergence");
		this.vbox4.Add (this.convergenceProgressBar);
		global::Gtk.Box.BoxChild w57 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.convergenceProgressBar]));
		w57.Position = 1;
		w57.Expand = false;
		w57.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.diversityProgressBar = new global::Gtk.ProgressBar ();
		this.diversityProgressBar.Name = "diversityProgressBar";
		this.diversityProgressBar.Text = global::Mono.Unix.Catalog.GetString ("Diversity");
		this.vbox4.Add (this.diversityProgressBar);
		global::Gtk.Box.BoxChild w58 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.diversityProgressBar]));
		w58.Position = 2;
		w58.Expand = false;
		w58.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.diversityFProgressBar = new global::Gtk.ProgressBar ();
		this.diversityFProgressBar.Name = "diversityFProgressBar";
		this.diversityFProgressBar.Text = global::Mono.Unix.Catalog.GetString ("DiversityF");
		this.vbox4.Add (this.diversityFProgressBar);
		global::Gtk.Box.BoxChild w59 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.diversityFProgressBar]));
		w59.Position = 3;
		w59.Expand = false;
		w59.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.convergenceFProgressBar = new global::Gtk.ProgressBar ();
		this.convergenceFProgressBar.Name = "convergenceFProgressBar";
		this.convergenceFProgressBar.Text = global::Mono.Unix.Catalog.GetString ("ConvergenceF");
		this.vbox4.Add (this.convergenceFProgressBar);
		global::Gtk.Box.BoxChild w60 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.convergenceFProgressBar]));
		w60.Position = 4;
		w60.Expand = false;
		w60.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.duplicateProgressBar = new global::Gtk.ProgressBar ();
		this.duplicateProgressBar.Name = "duplicateProgressBar";
		this.duplicateProgressBar.Text = global::Mono.Unix.Catalog.GetString ("Duplicates (%)");
		this.vbox4.Add (this.duplicateProgressBar);
		global::Gtk.Box.BoxChild w61 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.duplicateProgressBar]));
		w61.Position = 5;
		w61.Expand = false;
		w61.Fill = false;
		// Container child vbox4.Gtk.Box+BoxChild
		this.fitnessProgressBar = new global::Gtk.ProgressBar ();
		this.fitnessProgressBar.Name = "fitnessProgressBar";
		this.fitnessProgressBar.Text = global::Mono.Unix.Catalog.GetString ("C9 Fitness");
		this.vbox4.Add (this.fitnessProgressBar);
		global::Gtk.Box.BoxChild w62 = ((global::Gtk.Box.BoxChild)(this.vbox4 [this.fitnessProgressBar]));
		w62.Position = 6;
		w62.Expand = false;
		w62.Fill = false;
		this.GtkAlignment8.Add (this.vbox4);
		this.frame6.Add (this.GtkAlignment8);
		this.GtkLabel31 = new global::Gtk.Label ();
		this.GtkLabel31.Name = "GtkLabel31";
		this.GtkLabel31.LabelProp = global::Mono.Unix.Catalog.GetString ("Statistics");
		this.GtkLabel31.UseMarkup = true;
		this.frame6.LabelWidget = this.GtkLabel31;
		this.vbox5.Add (this.frame6);
		global::Gtk.Box.BoxChild w65 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame6]));
		w65.Position = 0;
		w65.Expand = false;
		w65.Fill = false;
		// Container child vbox5.Gtk.Box+BoxChild
		this.frame8 = new global::Gtk.Frame ();
		this.frame8.Name = "frame8";
		this.frame8.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child frame8.Gtk.Container+ContainerChild
		this.GtkAlignment7 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment7.Name = "GtkAlignment7";
		this.GtkAlignment7.LeftPadding = ((uint)(12));
		this.GtkAlignment7.BorderWidth = ((uint)(5));
		// Container child GtkAlignment7.Gtk.Container+ContainerChild
		this.vbox6 = new global::Gtk.VBox ();
		this.vbox6.Name = "vbox6";
		this.vbox6.Spacing = 6;
		// Container child vbox6.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox ();
		this.hbox2.Name = "hbox2";
		this.hbox2.Homogeneous = true;
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBarZero = new global::Gtk.ProgressBar ();
		this.distributionProgressBarZero.Name = "distributionProgressBarZero";
		this.distributionProgressBarZero.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBarZero);
		global::Gtk.Box.BoxChild w66 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBarZero]));
		w66.Position = 0;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar1 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar1.Name = "distributionProgressBar1";
		this.distributionProgressBar1.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar1);
		global::Gtk.Box.BoxChild w67 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar1]));
		w67.Position = 1;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar2 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar2.Name = "distributionProgressBar2";
		this.distributionProgressBar2.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar2);
		global::Gtk.Box.BoxChild w68 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar2]));
		w68.Position = 2;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar3 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar3.Name = "distributionProgressBar3";
		this.distributionProgressBar3.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar3);
		global::Gtk.Box.BoxChild w69 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar3]));
		w69.Position = 3;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar4 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar4.Name = "distributionProgressBar4";
		this.distributionProgressBar4.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar4);
		global::Gtk.Box.BoxChild w70 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar4]));
		w70.Position = 4;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar5 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar5.Name = "distributionProgressBar5";
		this.distributionProgressBar5.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar5);
		global::Gtk.Box.BoxChild w71 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar5]));
		w71.Position = 5;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar6 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar6.Name = "distributionProgressBar6";
		this.distributionProgressBar6.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar6);
		global::Gtk.Box.BoxChild w72 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar6]));
		w72.Position = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar7 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar7.Name = "distributionProgressBar7";
		this.distributionProgressBar7.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar7);
		global::Gtk.Box.BoxChild w73 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar7]));
		w73.Position = 7;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar8 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar8.Name = "distributionProgressBar8";
		this.distributionProgressBar8.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar8);
		global::Gtk.Box.BoxChild w74 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar8]));
		w74.Position = 8;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar9 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar9.Name = "distributionProgressBar9";
		this.distributionProgressBar9.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar9);
		global::Gtk.Box.BoxChild w75 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar9]));
		w75.Position = 9;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar10 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar10.Name = "distributionProgressBar10";
		this.distributionProgressBar10.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar10);
		global::Gtk.Box.BoxChild w76 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar10]));
		w76.Position = 10;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar11 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar11.Name = "distributionProgressBar11";
		this.distributionProgressBar11.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar11);
		global::Gtk.Box.BoxChild w77 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar11]));
		w77.Position = 11;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar12 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar12.Name = "distributionProgressBar12";
		this.distributionProgressBar12.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar12);
		global::Gtk.Box.BoxChild w78 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar12]));
		w78.Position = 12;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar13 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar13.Name = "distributionProgressBar13";
		this.distributionProgressBar13.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar13);
		global::Gtk.Box.BoxChild w79 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar13]));
		w79.Position = 13;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar14 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar14.Name = "distributionProgressBar14";
		this.distributionProgressBar14.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar14);
		global::Gtk.Box.BoxChild w80 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar14]));
		w80.Position = 14;
		// Container child hbox2.Gtk.Box+BoxChild
		this.distributionProgressBar15 = new global::Gtk.ProgressBar ();
		this.distributionProgressBar15.Name = "distributionProgressBar15";
		this.distributionProgressBar15.Orientation = ((global::Gtk.ProgressBarOrientation)(2));
		this.hbox2.Add (this.distributionProgressBar15);
		global::Gtk.Box.BoxChild w81 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.distributionProgressBar15]));
		w81.Position = 15;
		this.vbox6.Add (this.hbox2);
		global::Gtk.Box.BoxChild w82 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.hbox2]));
		w82.Position = 0;
		w82.Expand = false;
		w82.Fill = false;
		// Container child vbox6.Gtk.Box+BoxChild
		this.distributionHScale = new global::Gtk.HScale (null);
		this.distributionHScale.CanFocus = true;
		this.distributionHScale.Name = "distributionHScale";
		this.distributionHScale.Adjustment.Upper = 100;
		this.distributionHScale.Adjustment.PageIncrement = 10;
		this.distributionHScale.Adjustment.StepIncrement = 1;
		this.distributionHScale.Adjustment.Value = 100;
		this.distributionHScale.DrawValue = false;
		this.distributionHScale.Digits = 0;
		this.distributionHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox6.Add (this.distributionHScale);
		global::Gtk.Box.BoxChild w83 = ((global::Gtk.Box.BoxChild)(this.vbox6 [this.distributionHScale]));
		w83.Position = 1;
		w83.Expand = false;
		w83.Fill = false;
		this.GtkAlignment7.Add (this.vbox6);
		this.frame8.Add (this.GtkAlignment7);
		this.GtkLabel32 = new global::Gtk.Label ();
		this.GtkLabel32.Name = "GtkLabel32";
		this.GtkLabel32.LabelProp = global::Mono.Unix.Catalog.GetString ("Distribution of Fitness [0-1]");
		this.GtkLabel32.UseMarkup = true;
		this.frame8.LabelWidget = this.GtkLabel32;
		this.vbox5.Add (this.frame8);
		global::Gtk.Box.BoxChild w86 = ((global::Gtk.Box.BoxChild)(this.vbox5 [this.frame8]));
		w86.Position = 1;
		w86.Expand = false;
		w86.Fill = false;
		this.mainNotebook.Add (this.vbox5);
		// Notebook tab
		this.monitorTabLabel = new global::Gtk.Label ();
		this.monitorTabLabel.Name = "monitorTabLabel";
		this.monitorTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Monitor");
		this.mainNotebook.SetTabLabel (this.vbox5, this.monitorTabLabel);
		this.monitorTabLabel.ShowAll ();
		// Container child mainNotebook.Gtk.Notebook+NotebookChild
		this.populationScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.populationScrolledWindow.CanFocus = true;
		this.populationScrolledWindow.Name = "populationScrolledWindow";
		this.populationScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		this.mainNotebook.Add (this.populationScrolledWindow);
		global::Gtk.Notebook.NotebookChild w88 = ((global::Gtk.Notebook.NotebookChild)(this.mainNotebook [this.populationScrolledWindow]));
		w88.Position = 1;
		// Notebook tab
		this.genoTypicTabLabel = new global::Gtk.Label ();
		this.genoTypicTabLabel.Name = "genoTypicTabLabel";
		this.genoTypicTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Genotypic View");
		this.mainNotebook.SetTabLabel (this.populationScrolledWindow, this.genoTypicTabLabel);
		this.genoTypicTabLabel.ShowAll ();
		// Container child mainNotebook.Gtk.Notebook+NotebookChild
		this.GtkScrolledWindow8 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow8.Name = "GtkScrolledWindow8";
		this.GtkScrolledWindow8.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow8.Gtk.Container+ContainerChild
		this.sourceCodeTextView = new global::Gtk.TextView ();
		this.sourceCodeTextView.CanFocus = true;
		this.sourceCodeTextView.Name = "sourceCodeTextView";
		this.sourceCodeTextView.Editable = false;
		this.sourceCodeTextView.CursorVisible = false;
		this.GtkScrolledWindow8.Add (this.sourceCodeTextView);
		this.mainNotebook.Add (this.GtkScrolledWindow8);
		global::Gtk.Notebook.NotebookChild w90 = ((global::Gtk.Notebook.NotebookChild)(this.mainNotebook [this.GtkScrolledWindow8]));
		w90.Position = 2;
		// Notebook tab
		this.sourceCodeTabLabel = new global::Gtk.Label ();
		this.sourceCodeTabLabel.Name = "sourceCodeTabLabel";
		this.sourceCodeTabLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Source Code");
		this.mainNotebook.SetTabLabel (this.GtkScrolledWindow8, this.sourceCodeTabLabel);
		this.sourceCodeTabLabel.ShowAll ();
		this.hpaned2.Add (this.mainNotebook);
		global::Gtk.Paned.PanedChild w91 = ((global::Gtk.Paned.PanedChild)(this.hpaned2 [this.mainNotebook]));
		w91.Resize = false;
		// Container child hpaned2.Gtk.Paned+PanedChild
		this.notebook5 = new global::Gtk.Notebook ();
		this.notebook5.CanFocus = true;
		this.notebook5.Name = "notebook5";
		this.notebook5.CurrentPage = 1;
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox3 = new global::Gtk.VBox ();
		this.vbox3.Name = "vbox3";
		this.vbox3.Spacing = 6;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox9 = new global::Gtk.HBox ();
		this.hbox9.Name = "hbox9";
		this.hbox9.Homogeneous = true;
		this.hbox9.Spacing = 6;
		// Container child hbox9.Gtk.Box+BoxChild
		this.crossoverEnabledCheckButton = new global::Gtk.CheckButton ();
		this.crossoverEnabledCheckButton.CanFocus = true;
		this.crossoverEnabledCheckButton.Name = "crossoverEnabledCheckButton";
		this.crossoverEnabledCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.crossoverEnabledCheckButton.Active = true;
		this.crossoverEnabledCheckButton.DrawIndicator = true;
		this.crossoverEnabledCheckButton.UseUnderline = true;
		this.hbox9.Add (this.crossoverEnabledCheckButton);
		global::Gtk.Box.BoxChild w92 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.crossoverEnabledCheckButton]));
		w92.Position = 0;
		// Container child hbox9.Gtk.Box+BoxChild
		this.crossoverAllowDuplicatesCheckButton = new global::Gtk.CheckButton ();
		this.crossoverAllowDuplicatesCheckButton.CanFocus = true;
		this.crossoverAllowDuplicatesCheckButton.Name = "crossoverAllowDuplicatesCheckButton";
		this.crossoverAllowDuplicatesCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Allow Duplicates");
		this.crossoverAllowDuplicatesCheckButton.Active = true;
		this.crossoverAllowDuplicatesCheckButton.DrawIndicator = true;
		this.crossoverAllowDuplicatesCheckButton.UseUnderline = true;
		this.hbox9.Add (this.crossoverAllowDuplicatesCheckButton);
		global::Gtk.Box.BoxChild w93 = ((global::Gtk.Box.BoxChild)(this.hbox9 [this.crossoverAllowDuplicatesCheckButton]));
		w93.Position = 1;
		this.vbox3.Add (this.hbox9);
		global::Gtk.Box.BoxChild w94 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox9]));
		w94.Position = 0;
		w94.Expand = false;
		w94.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.label3 = new global::Gtk.Label ();
		this.label3.Name = "label3";
		this.label3.LabelProp = global::Mono.Unix.Catalog.GetString ("Probability");
		this.vbox3.Add (this.label3);
		global::Gtk.Box.BoxChild w95 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.label3]));
		w95.Position = 1;
		w95.Expand = false;
		w95.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.crossoverProbabilityHScale = new global::Gtk.HScale (null);
		this.crossoverProbabilityHScale.CanFocus = true;
		this.crossoverProbabilityHScale.Name = "crossoverProbabilityHScale";
		this.crossoverProbabilityHScale.Adjustment.Upper = 1;
		this.crossoverProbabilityHScale.Adjustment.PageIncrement = 0.1;
		this.crossoverProbabilityHScale.Adjustment.StepIncrement = 0.01;
		this.crossoverProbabilityHScale.Adjustment.Value = 0.31;
		this.crossoverProbabilityHScale.DrawValue = true;
		this.crossoverProbabilityHScale.Digits = 2;
		this.crossoverProbabilityHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox3.Add (this.crossoverProbabilityHScale);
		global::Gtk.Box.BoxChild w96 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.crossoverProbabilityHScale]));
		w96.Position = 2;
		w96.Expand = false;
		w96.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.hbox8 = new global::Gtk.HBox ();
		this.hbox8.Name = "hbox8";
		this.hbox8.Homogeneous = true;
		this.hbox8.Spacing = 6;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame4 = new global::Gtk.Frame ();
		this.frame4.Name = "frame4";
		this.frame4.BorderWidth = ((uint)(1));
		// Container child frame4.Gtk.Container+ContainerChild
		this.GtkAlignment = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment.Name = "GtkAlignment";
		this.GtkAlignment.LeftPadding = ((uint)(12));
		this.GtkAlignment.BorderWidth = ((uint)(5));
		// Container child GtkAlignment.Gtk.Container+ContainerChild
		this.vbox10 = new global::Gtk.VBox ();
		this.vbox10.Name = "vbox10";
		this.vbox10.Spacing = 6;
		// Container child vbox10.Gtk.Box+BoxChild
		this.crossoverTypeSingleRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Single Point"));
		this.crossoverTypeSingleRadioButton.CanFocus = true;
		this.crossoverTypeSingleRadioButton.Name = "crossoverTypeSingleRadioButton";
		this.crossoverTypeSingleRadioButton.DrawIndicator = true;
		this.crossoverTypeSingleRadioButton.UseUnderline = true;
		this.crossoverTypeSingleRadioButton.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox10.Add (this.crossoverTypeSingleRadioButton);
		global::Gtk.Box.BoxChild w97 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.crossoverTypeSingleRadioButton]));
		w97.Position = 0;
		w97.Expand = false;
		w97.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.crossoverTypeDoubleRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Double Point"));
		this.crossoverTypeDoubleRadioButton.CanFocus = true;
		this.crossoverTypeDoubleRadioButton.Name = "crossoverTypeDoubleRadioButton";
		this.crossoverTypeDoubleRadioButton.DrawIndicator = true;
		this.crossoverTypeDoubleRadioButton.UseUnderline = true;
		this.crossoverTypeDoubleRadioButton.Group = this.crossoverTypeSingleRadioButton.Group;
		this.vbox10.Add (this.crossoverTypeDoubleRadioButton);
		global::Gtk.Box.BoxChild w98 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.crossoverTypeDoubleRadioButton]));
		w98.Position = 1;
		w98.Expand = false;
		w98.Fill = false;
		// Container child vbox10.Gtk.Box+BoxChild
		this.crossoverTypeDoubleOrderedRadioButton = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Double Point Ordered"));
		this.crossoverTypeDoubleOrderedRadioButton.CanFocus = true;
		this.crossoverTypeDoubleOrderedRadioButton.Name = "crossoverTypeDoubleOrderedRadioButton";
		this.crossoverTypeDoubleOrderedRadioButton.DrawIndicator = true;
		this.crossoverTypeDoubleOrderedRadioButton.UseUnderline = true;
		this.crossoverTypeDoubleOrderedRadioButton.Group = this.crossoverTypeSingleRadioButton.Group;
		this.vbox10.Add (this.crossoverTypeDoubleOrderedRadioButton);
		global::Gtk.Box.BoxChild w99 = ((global::Gtk.Box.BoxChild)(this.vbox10 [this.crossoverTypeDoubleOrderedRadioButton]));
		w99.Position = 2;
		w99.Expand = false;
		w99.Fill = false;
		this.GtkAlignment.Add (this.vbox10);
		this.frame4.Add (this.GtkAlignment);
		this.GtkLabel22 = new global::Gtk.Label ();
		this.GtkLabel22.Name = "GtkLabel22";
		this.GtkLabel22.LabelProp = global::Mono.Unix.Catalog.GetString ("Crossover Type");
		this.GtkLabel22.UseMarkup = true;
		this.frame4.LabelWidget = this.GtkLabel22;
		this.hbox8.Add (this.frame4);
		global::Gtk.Box.BoxChild w102 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.frame4]));
		w102.Position = 0;
		// Container child hbox8.Gtk.Box+BoxChild
		this.frame7 = new global::Gtk.Frame ();
		this.frame7.Name = "frame7";
		this.frame7.BorderWidth = ((uint)(1));
		// Container child frame7.Gtk.Container+ContainerChild
		this.GtkAlignment2 = new global::Gtk.Alignment (0F, 0F, 1F, 1F);
		this.GtkAlignment2.Name = "GtkAlignment2";
		this.GtkAlignment2.LeftPadding = ((uint)(12));
		this.GtkAlignment2.BorderWidth = ((uint)(5));
		// Container child GtkAlignment2.Gtk.Container+ContainerChild
		this.vbox11 = new global::Gtk.VBox ();
		this.vbox11.Name = "vbox11";
		this.vbox11.Spacing = 6;
		// Container child vbox11.Gtk.Box+BoxChild
		this.crossoverReplacementGenerational = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Generic Replacement"));
		this.crossoverReplacementGenerational.CanFocus = true;
		this.crossoverReplacementGenerational.Name = "crossoverReplacementGenerational";
		this.crossoverReplacementGenerational.DrawIndicator = true;
		this.crossoverReplacementGenerational.UseUnderline = true;
		this.crossoverReplacementGenerational.Group = new global::GLib.SList (global::System.IntPtr.Zero);
		this.vbox11.Add (this.crossoverReplacementGenerational);
		global::Gtk.Box.BoxChild w103 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.crossoverReplacementGenerational]));
		w103.Position = 0;
		w103.Expand = false;
		w103.Fill = false;
		// Container child vbox11.Gtk.Box+BoxChild
		this.crossoverReplacementDeleteLast = new global::Gtk.RadioButton (global::Mono.Unix.Catalog.GetString ("Delete Last"));
		this.crossoverReplacementDeleteLast.CanFocus = true;
		this.crossoverReplacementDeleteLast.Name = "crossoverReplacementDeleteLast";
		this.crossoverReplacementDeleteLast.DrawIndicator = true;
		this.crossoverReplacementDeleteLast.UseUnderline = true;
		this.crossoverReplacementDeleteLast.Group = this.crossoverReplacementGenerational.Group;
		this.vbox11.Add (this.crossoverReplacementDeleteLast);
		global::Gtk.Box.BoxChild w104 = ((global::Gtk.Box.BoxChild)(this.vbox11 [this.crossoverReplacementDeleteLast]));
		w104.Position = 1;
		w104.Expand = false;
		w104.Fill = false;
		this.GtkAlignment2.Add (this.vbox11);
		this.frame7.Add (this.GtkAlignment2);
		this.GtkLabel25 = new global::Gtk.Label ();
		this.GtkLabel25.Name = "GtkLabel25";
		this.GtkLabel25.LabelProp = global::Mono.Unix.Catalog.GetString ("Replacement Type");
		this.GtkLabel25.UseMarkup = true;
		this.frame7.LabelWidget = this.GtkLabel25;
		this.hbox8.Add (this.frame7);
		global::Gtk.Box.BoxChild w107 = ((global::Gtk.Box.BoxChild)(this.hbox8 [this.frame7]));
		w107.Position = 1;
		this.vbox3.Add (this.hbox8);
		global::Gtk.Box.BoxChild w108 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.hbox8]));
		w108.Position = 3;
		w108.Expand = false;
		w108.Fill = false;
		// Container child vbox3.Gtk.Box+BoxChild
		this.GtkScrolledWindow = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow.Name = "GtkScrolledWindow";
		this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
		this.crossoverTextView = new global::Gtk.TextView ();
		this.crossoverTextView.CanFocus = true;
		this.crossoverTextView.Name = "crossoverTextView";
		this.crossoverTextView.Editable = false;
		this.crossoverTextView.CursorVisible = false;
		this.crossoverTextView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow.Add (this.crossoverTextView);
		this.vbox3.Add (this.GtkScrolledWindow);
		global::Gtk.Box.BoxChild w110 = ((global::Gtk.Box.BoxChild)(this.vbox3 [this.GtkScrolledWindow]));
		w110.PackType = ((global::Gtk.PackType)(1));
		w110.Position = 4;
		this.notebook5.Add (this.vbox3);
		// Notebook tab
		this.label7 = new global::Gtk.Label ();
		this.label7.Name = "label7";
		this.label7.LabelProp = global::Mono.Unix.Catalog.GetString ("Crossover");
		this.notebook5.SetTabLabel (this.vbox3, this.label7);
		this.label7.ShowAll ();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox12 = new global::Gtk.VBox ();
		this.vbox12.Name = "vbox12";
		this.vbox12.Spacing = 6;
		// Container child vbox12.Gtk.Box+BoxChild
		this.hbox7 = new global::Gtk.HBox ();
		this.hbox7.Name = "hbox7";
		this.hbox7.Spacing = 6;
		// Container child hbox7.Gtk.Box+BoxChild
		this.binaryMutateEnabledCheckButton = new global::Gtk.CheckButton ();
		this.binaryMutateEnabledCheckButton.CanFocus = true;
		this.binaryMutateEnabledCheckButton.Name = "binaryMutateEnabledCheckButton";
		this.binaryMutateEnabledCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.binaryMutateEnabledCheckButton.DrawIndicator = true;
		this.binaryMutateEnabledCheckButton.UseUnderline = true;
		this.hbox7.Add (this.binaryMutateEnabledCheckButton);
		global::Gtk.Box.BoxChild w112 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.binaryMutateEnabledCheckButton]));
		w112.Position = 0;
		// Container child hbox7.Gtk.Box+BoxChild
		this.binaryMutateAllowDuplicatesCheckButton = new global::Gtk.CheckButton ();
		this.binaryMutateAllowDuplicatesCheckButton.CanFocus = true;
		this.binaryMutateAllowDuplicatesCheckButton.Name = "binaryMutateAllowDuplicatesCheckButton";
		this.binaryMutateAllowDuplicatesCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Allow Duplicates");
		this.binaryMutateAllowDuplicatesCheckButton.Active = true;
		this.binaryMutateAllowDuplicatesCheckButton.DrawIndicator = true;
		this.binaryMutateAllowDuplicatesCheckButton.UseUnderline = true;
		this.hbox7.Add (this.binaryMutateAllowDuplicatesCheckButton);
		global::Gtk.Box.BoxChild w113 = ((global::Gtk.Box.BoxChild)(this.hbox7 [this.binaryMutateAllowDuplicatesCheckButton]));
		w113.Position = 1;
		this.vbox12.Add (this.hbox7);
		global::Gtk.Box.BoxChild w114 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.hbox7]));
		w114.Position = 0;
		w114.Expand = false;
		w114.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.label4 = new global::Gtk.Label ();
		this.label4.Name = "label4";
		this.label4.LabelProp = global::Mono.Unix.Catalog.GetString ("Probability");
		this.vbox12.Add (this.label4);
		global::Gtk.Box.BoxChild w115 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.label4]));
		w115.Position = 1;
		w115.Expand = false;
		w115.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.binaryMutateProbabilityHScale = new global::Gtk.HScale (null);
		this.binaryMutateProbabilityHScale.CanFocus = true;
		this.binaryMutateProbabilityHScale.Name = "binaryMutateProbabilityHScale";
		this.binaryMutateProbabilityHScale.Adjustment.Upper = 1;
		this.binaryMutateProbabilityHScale.Adjustment.PageIncrement = 0.1;
		this.binaryMutateProbabilityHScale.Adjustment.StepIncrement = 0.01;
		this.binaryMutateProbabilityHScale.Adjustment.Value = 0.4;
		this.binaryMutateProbabilityHScale.DrawValue = true;
		this.binaryMutateProbabilityHScale.Digits = 2;
		this.binaryMutateProbabilityHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox12.Add (this.binaryMutateProbabilityHScale);
		global::Gtk.Box.BoxChild w116 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.binaryMutateProbabilityHScale]));
		w116.Position = 2;
		w116.Expand = false;
		w116.Fill = false;
		// Container child vbox12.Gtk.Box+BoxChild
		this.GtkScrolledWindow1 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow1.Name = "GtkScrolledWindow1";
		this.GtkScrolledWindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow1.Gtk.Container+ContainerChild
		this.binaryMutateTextView = new global::Gtk.TextView ();
		this.binaryMutateTextView.CanFocus = true;
		this.binaryMutateTextView.Name = "binaryMutateTextView";
		this.binaryMutateTextView.Editable = false;
		this.binaryMutateTextView.CursorVisible = false;
		this.binaryMutateTextView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow1.Add (this.binaryMutateTextView);
		this.vbox12.Add (this.GtkScrolledWindow1);
		global::Gtk.Box.BoxChild w118 = ((global::Gtk.Box.BoxChild)(this.vbox12 [this.GtkScrolledWindow1]));
		w118.Position = 3;
		this.notebook5.Add (this.vbox12);
		global::Gtk.Notebook.NotebookChild w119 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5 [this.vbox12]));
		w119.Position = 1;
		// Notebook tab
		this.label9 = new global::Gtk.Label ();
		this.label9.Name = "label9";
		this.label9.LabelProp = global::Mono.Unix.Catalog.GetString ("Binary Mutate");
		this.notebook5.SetTabLabel (this.vbox12, this.label9);
		this.label9.ShowAll ();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox13 = new global::Gtk.VBox ();
		this.vbox13.Name = "vbox13";
		this.vbox13.Spacing = 6;
		// Container child vbox13.Gtk.Box+BoxChild
		this.eliteEnabledCheckButton = new global::Gtk.CheckButton ();
		this.eliteEnabledCheckButton.CanFocus = true;
		this.eliteEnabledCheckButton.Name = "eliteEnabledCheckButton";
		this.eliteEnabledCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.eliteEnabledCheckButton.Active = true;
		this.eliteEnabledCheckButton.DrawIndicator = true;
		this.eliteEnabledCheckButton.UseUnderline = true;
		this.vbox13.Add (this.eliteEnabledCheckButton);
		global::Gtk.Box.BoxChild w120 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.eliteEnabledCheckButton]));
		w120.Position = 0;
		w120.Expand = false;
		w120.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.label8 = new global::Gtk.Label ();
		this.label8.Name = "label8";
		this.label8.LabelProp = global::Mono.Unix.Catalog.GetString ("Percentatge");
		this.vbox13.Add (this.label8);
		global::Gtk.Box.BoxChild w121 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.label8]));
		w121.Position = 1;
		w121.Expand = false;
		w121.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.elitePercentageHScale = new global::Gtk.HScale (null);
		this.elitePercentageHScale.CanFocus = true;
		this.elitePercentageHScale.Name = "elitePercentageHScale";
		this.elitePercentageHScale.Adjustment.Upper = 100;
		this.elitePercentageHScale.Adjustment.PageIncrement = 10;
		this.elitePercentageHScale.Adjustment.StepIncrement = 1;
		this.elitePercentageHScale.Adjustment.Value = 100;
		this.elitePercentageHScale.DrawValue = true;
		this.elitePercentageHScale.Digits = 0;
		this.elitePercentageHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox13.Add (this.elitePercentageHScale);
		global::Gtk.Box.BoxChild w122 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.elitePercentageHScale]));
		w122.Position = 2;
		w122.Expand = false;
		w122.Fill = false;
		// Container child vbox13.Gtk.Box+BoxChild
		this.GtkScrolledWindow3 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow3.Name = "GtkScrolledWindow3";
		this.GtkScrolledWindow3.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow3.Gtk.Container+ContainerChild
		this.eliteTextView = new global::Gtk.TextView ();
		this.eliteTextView.CanFocus = true;
		this.eliteTextView.Name = "eliteTextView";
		this.eliteTextView.Editable = false;
		this.eliteTextView.CursorVisible = false;
		this.eliteTextView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow3.Add (this.eliteTextView);
		this.vbox13.Add (this.GtkScrolledWindow3);
		global::Gtk.Box.BoxChild w124 = ((global::Gtk.Box.BoxChild)(this.vbox13 [this.GtkScrolledWindow3]));
		w124.Position = 3;
		this.notebook5.Add (this.vbox13);
		global::Gtk.Notebook.NotebookChild w125 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5 [this.vbox13]));
		w125.Position = 2;
		// Notebook tab
		this.label10 = new global::Gtk.Label ();
		this.label10.Name = "label10";
		this.label10.LabelProp = global::Mono.Unix.Catalog.GetString ("Elite");
		this.notebook5.SetTabLabel (this.vbox13, this.label10);
		this.label10.ShowAll ();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox15 = new global::Gtk.VBox ();
		this.vbox15.Name = "vbox15";
		this.vbox15.Spacing = 6;
		// Container child vbox15.Gtk.Box+BoxChild
		this.hbox10 = new global::Gtk.HBox ();
		this.hbox10.Name = "hbox10";
		this.hbox10.Spacing = 6;
		// Container child hbox10.Gtk.Box+BoxChild
		this.randomReplaceEnabledCheckButton = new global::Gtk.CheckButton ();
		this.randomReplaceEnabledCheckButton.CanFocus = true;
		this.randomReplaceEnabledCheckButton.Name = "randomReplaceEnabledCheckButton";
		this.randomReplaceEnabledCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.randomReplaceEnabledCheckButton.DrawIndicator = true;
		this.randomReplaceEnabledCheckButton.UseUnderline = true;
		this.hbox10.Add (this.randomReplaceEnabledCheckButton);
		global::Gtk.Box.BoxChild w126 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.randomReplaceEnabledCheckButton]));
		w126.Position = 0;
		// Container child hbox10.Gtk.Box+BoxChild
		this.randomReplaceAllowDuplicatesCheckButton = new global::Gtk.CheckButton ();
		this.randomReplaceAllowDuplicatesCheckButton.CanFocus = true;
		this.randomReplaceAllowDuplicatesCheckButton.Name = "randomReplaceAllowDuplicatesCheckButton";
		this.randomReplaceAllowDuplicatesCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Allow Duplicates");
		this.randomReplaceAllowDuplicatesCheckButton.Active = true;
		this.randomReplaceAllowDuplicatesCheckButton.DrawIndicator = true;
		this.randomReplaceAllowDuplicatesCheckButton.UseUnderline = true;
		this.hbox10.Add (this.randomReplaceAllowDuplicatesCheckButton);
		global::Gtk.Box.BoxChild w127 = ((global::Gtk.Box.BoxChild)(this.hbox10 [this.randomReplaceAllowDuplicatesCheckButton]));
		w127.Position = 1;
		this.vbox15.Add (this.hbox10);
		global::Gtk.Box.BoxChild w128 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.hbox10]));
		w128.Position = 0;
		w128.Expand = false;
		w128.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.label18 = new global::Gtk.Label ();
		this.label18.Name = "label18";
		this.label18.LabelProp = global::Mono.Unix.Catalog.GetString ("Percentage");
		this.vbox15.Add (this.label18);
		global::Gtk.Box.BoxChild w129 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.label18]));
		w129.Position = 1;
		w129.Expand = false;
		w129.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.randomReplacePercentageHScale = new global::Gtk.HScale (null);
		this.randomReplacePercentageHScale.CanFocus = true;
		this.randomReplacePercentageHScale.Name = "randomReplacePercentageHScale";
		this.randomReplacePercentageHScale.Adjustment.Upper = 100;
		this.randomReplacePercentageHScale.Adjustment.PageIncrement = 10;
		this.randomReplacePercentageHScale.Adjustment.StepIncrement = 1;
		this.randomReplacePercentageHScale.DrawValue = true;
		this.randomReplacePercentageHScale.Digits = 0;
		this.randomReplacePercentageHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox15.Add (this.randomReplacePercentageHScale);
		global::Gtk.Box.BoxChild w130 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.randomReplacePercentageHScale]));
		w130.Position = 2;
		w130.Expand = false;
		w130.Fill = false;
		// Container child vbox15.Gtk.Box+BoxChild
		this.GtkScrolledWindow5 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow5.Name = "GtkScrolledWindow5";
		this.GtkScrolledWindow5.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow5.Gtk.Container+ContainerChild
		this.randomReplaceTextView = new global::Gtk.TextView ();
		this.randomReplaceTextView.CanFocus = true;
		this.randomReplaceTextView.Name = "randomReplaceTextView";
		this.randomReplaceTextView.Editable = false;
		this.randomReplaceTextView.CursorVisible = false;
		this.randomReplaceTextView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow5.Add (this.randomReplaceTextView);
		this.vbox15.Add (this.GtkScrolledWindow5);
		global::Gtk.Box.BoxChild w132 = ((global::Gtk.Box.BoxChild)(this.vbox15 [this.GtkScrolledWindow5]));
		w132.Position = 3;
		this.notebook5.Add (this.vbox15);
		global::Gtk.Notebook.NotebookChild w133 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5 [this.vbox15]));
		w133.Position = 3;
		// Notebook tab
		this.label14 = new global::Gtk.Label ();
		this.label14.Name = "label14";
		this.label14.LabelProp = global::Mono.Unix.Catalog.GetString ("Random Replace");
		this.notebook5.SetTabLabel (this.vbox15, this.label14);
		this.label14.ShowAll ();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox16 = new global::Gtk.VBox ();
		this.vbox16.Name = "vbox16";
		this.vbox16.Spacing = 6;
		// Container child vbox16.Gtk.Box+BoxChild
		this.swapMutateEnabledCheckButton = new global::Gtk.CheckButton ();
		this.swapMutateEnabledCheckButton.CanFocus = true;
		this.swapMutateEnabledCheckButton.Name = "swapMutateEnabledCheckButton";
		this.swapMutateEnabledCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.swapMutateEnabledCheckButton.DrawIndicator = true;
		this.swapMutateEnabledCheckButton.UseUnderline = true;
		this.vbox16.Add (this.swapMutateEnabledCheckButton);
		global::Gtk.Box.BoxChild w134 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.swapMutateEnabledCheckButton]));
		w134.Position = 0;
		w134.Expand = false;
		w134.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.label19 = new global::Gtk.Label ();
		this.label19.Name = "label19";
		this.label19.LabelProp = global::Mono.Unix.Catalog.GetString ("Probability");
		this.vbox16.Add (this.label19);
		global::Gtk.Box.BoxChild w135 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.label19]));
		w135.Position = 1;
		w135.Expand = false;
		w135.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.swapMutateProbabilityHScale = new global::Gtk.HScale (null);
		this.swapMutateProbabilityHScale.CanFocus = true;
		this.swapMutateProbabilityHScale.Name = "swapMutateProbabilityHScale";
		this.swapMutateProbabilityHScale.Adjustment.Upper = 1;
		this.swapMutateProbabilityHScale.Adjustment.PageIncrement = 0.1;
		this.swapMutateProbabilityHScale.Adjustment.StepIncrement = 0.01;
		this.swapMutateProbabilityHScale.Adjustment.Value = 0.11;
		this.swapMutateProbabilityHScale.DrawValue = true;
		this.swapMutateProbabilityHScale.Digits = 2;
		this.swapMutateProbabilityHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox16.Add (this.swapMutateProbabilityHScale);
		global::Gtk.Box.BoxChild w136 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.swapMutateProbabilityHScale]));
		w136.Position = 2;
		w136.Expand = false;
		w136.Fill = false;
		// Container child vbox16.Gtk.Box+BoxChild
		this.GtkScrolledWindow6 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow6.Name = "GtkScrolledWindow6";
		this.GtkScrolledWindow6.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow6.Gtk.Container+ContainerChild
		this.swapMutateTextView = new global::Gtk.TextView ();
		this.swapMutateTextView.CanFocus = true;
		this.swapMutateTextView.Name = "swapMutateTextView";
		this.swapMutateTextView.Editable = false;
		this.swapMutateTextView.CursorVisible = false;
		this.swapMutateTextView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow6.Add (this.swapMutateTextView);
		this.vbox16.Add (this.GtkScrolledWindow6);
		global::Gtk.Box.BoxChild w138 = ((global::Gtk.Box.BoxChild)(this.vbox16 [this.GtkScrolledWindow6]));
		w138.Position = 3;
		this.notebook5.Add (this.vbox16);
		global::Gtk.Notebook.NotebookChild w139 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5 [this.vbox16]));
		w139.Position = 4;
		// Notebook tab
		this.label15 = new global::Gtk.Label ();
		this.label15.Name = "label15";
		this.label15.LabelProp = global::Mono.Unix.Catalog.GetString ("Swap Mutate");
		this.notebook5.SetTabLabel (this.vbox16, this.label15);
		this.label15.ShowAll ();
		// Container child notebook5.Gtk.Notebook+NotebookChild
		this.vbox17 = new global::Gtk.VBox ();
		this.vbox17.Name = "vbox17";
		this.vbox17.Spacing = 6;
		// Container child vbox17.Gtk.Box+BoxChild
		this.memoryEnabledCheckButton = new global::Gtk.CheckButton ();
		this.memoryEnabledCheckButton.CanFocus = true;
		this.memoryEnabledCheckButton.Name = "memoryEnabledCheckButton";
		this.memoryEnabledCheckButton.Label = global::Mono.Unix.Catalog.GetString ("Enabled");
		this.memoryEnabledCheckButton.Active = true;
		this.memoryEnabledCheckButton.DrawIndicator = true;
		this.memoryEnabledCheckButton.UseUnderline = true;
		this.vbox17.Add (this.memoryEnabledCheckButton);
		global::Gtk.Box.BoxChild w140 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.memoryEnabledCheckButton]));
		w140.Position = 0;
		w140.Expand = false;
		w140.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.label20 = new global::Gtk.Label ();
		this.label20.Name = "label20";
		this.label20.LabelProp = global::Mono.Unix.Catalog.GetString ("Memory Size");
		this.vbox17.Add (this.label20);
		global::Gtk.Box.BoxChild w141 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.label20]));
		w141.Position = 1;
		w141.Expand = false;
		w141.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.memorySizeHScale = new global::Gtk.HScale (null);
		this.memorySizeHScale.CanFocus = true;
		this.memorySizeHScale.Name = "memorySizeHScale";
		this.memorySizeHScale.Adjustment.Upper = 100;
		this.memorySizeHScale.Adjustment.PageIncrement = 10;
		this.memorySizeHScale.Adjustment.StepIncrement = 1;
		this.memorySizeHScale.Adjustment.Value = 20;
		this.memorySizeHScale.DrawValue = true;
		this.memorySizeHScale.Digits = 0;
		this.memorySizeHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox17.Add (this.memorySizeHScale);
		global::Gtk.Box.BoxChild w142 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.memorySizeHScale]));
		w142.Position = 2;
		w142.Expand = false;
		w142.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.label22 = new global::Gtk.Label ();
		this.label22.Name = "label22";
		this.label22.LabelProp = global::Mono.Unix.Catalog.GetString ("Update Period");
		this.vbox17.Add (this.label22);
		global::Gtk.Box.BoxChild w143 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.label22]));
		w143.Position = 3;
		w143.Expand = false;
		w143.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.memoryUpdateHScale = new global::Gtk.HScale (null);
		this.memoryUpdateHScale.CanFocus = true;
		this.memoryUpdateHScale.Name = "memoryUpdateHScale";
		this.memoryUpdateHScale.Adjustment.Upper = 100;
		this.memoryUpdateHScale.Adjustment.PageIncrement = 10;
		this.memoryUpdateHScale.Adjustment.StepIncrement = 1;
		this.memoryUpdateHScale.DrawValue = true;
		this.memoryUpdateHScale.Digits = 0;
		this.memoryUpdateHScale.ValuePos = ((global::Gtk.PositionType)(1));
		this.vbox17.Add (this.memoryUpdateHScale);
		global::Gtk.Box.BoxChild w144 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.memoryUpdateHScale]));
		w144.Position = 4;
		w144.Expand = false;
		w144.Fill = false;
		// Container child vbox17.Gtk.Box+BoxChild
		this.GtkScrolledWindow7 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow7.Name = "GtkScrolledWindow7";
		this.GtkScrolledWindow7.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow7.Gtk.Container+ContainerChild
		this.memoryTextView = new global::Gtk.TextView ();
		this.memoryTextView.CanFocus = true;
		this.memoryTextView.Name = "memoryTextView";
		this.memoryTextView.Editable = false;
		this.memoryTextView.CursorVisible = false;
		this.memoryTextView.WrapMode = ((global::Gtk.WrapMode)(2));
		this.GtkScrolledWindow7.Add (this.memoryTextView);
		this.vbox17.Add (this.GtkScrolledWindow7);
		global::Gtk.Box.BoxChild w146 = ((global::Gtk.Box.BoxChild)(this.vbox17 [this.GtkScrolledWindow7]));
		w146.Position = 5;
		this.notebook5.Add (this.vbox17);
		global::Gtk.Notebook.NotebookChild w147 = ((global::Gtk.Notebook.NotebookChild)(this.notebook5 [this.vbox17]));
		w147.Position = 5;
		// Notebook tab
		this.label16 = new global::Gtk.Label ();
		this.label16.Name = "label16";
		this.label16.LabelProp = global::Mono.Unix.Catalog.GetString ("Memory");
		this.notebook5.SetTabLabel (this.vbox17, this.label16);
		this.label16.ShowAll ();
		this.hpaned2.Add (this.notebook5);
		this.hbox1.Add (this.hpaned2);
		global::Gtk.Box.BoxChild w149 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.hpaned2]));
		w149.Position = 1;
		this.vpaned1.Add (this.hbox1);
		global::Gtk.Paned.PanedChild w150 = ((global::Gtk.Paned.PanedChild)(this.vpaned1 [this.hbox1]));
		w150.Resize = false;
		// Container child vpaned1.Gtk.Paned+PanedChild
		this.notebook1 = new global::Gtk.Notebook ();
		this.notebook1.CanFocus = true;
		this.notebook1.Name = "notebook1";
		this.notebook1.CurrentPage = 0;
		// Container child notebook1.Gtk.Notebook+NotebookChild
		this.scrolledwindow1 = new global::Gtk.ScrolledWindow ();
		this.scrolledwindow1.CanFocus = true;
		this.scrolledwindow1.Name = "scrolledwindow1";
		this.scrolledwindow1.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child scrolledwindow1.Gtk.Container+ContainerChild
		global::Gtk.Viewport w151 = new global::Gtk.Viewport ();
		w151.ShadowType = ((global::Gtk.ShadowType)(0));
		// Container child GtkViewport.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox ();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.GtkScrolledWindow2 = new global::Gtk.ScrolledWindow ();
		this.GtkScrolledWindow2.Name = "GtkScrolledWindow2";
		this.GtkScrolledWindow2.ShadowType = ((global::Gtk.ShadowType)(1));
		// Container child GtkScrolledWindow2.Gtk.Container+ContainerChild
		this.outputTextView = new global::Gtk.TextView ();
		this.outputTextView.CanFocus = true;
		this.outputTextView.Name = "outputTextView";
		this.outputTextView.CursorVisible = false;
		this.GtkScrolledWindow2.Add (this.outputTextView);
		this.vbox7.Add (this.GtkScrolledWindow2);
		global::Gtk.Box.BoxChild w153 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.GtkScrolledWindow2]));
		w153.Position = 1;
		// Container child vbox7.Gtk.Box+BoxChild
		this.UIManager.AddUiFromString ("<ui><toolbar name='toolbar1'><toolitem name='ClearAction' action='ClearAction'/></toolbar></ui>");
		this.toolbar1 = ((global::Gtk.Toolbar)(this.UIManager.GetWidget ("/toolbar1")));
		this.toolbar1.Name = "toolbar1";
		this.toolbar1.ShowArrow = false;
		this.vbox7.Add (this.toolbar1);
		global::Gtk.Box.BoxChild w154 = ((global::Gtk.Box.BoxChild)(this.vbox7 [this.toolbar1]));
		w154.Position = 2;
		w154.Expand = false;
		w154.Fill = false;
		w151.Add (this.vbox7);
		this.scrolledwindow1.Add (w151);
		this.notebook1.Add (this.scrolledwindow1);
		// Notebook tab
		this.label6 = new global::Gtk.Label ();
		this.label6.Name = "label6";
		this.label6.LabelProp = global::Mono.Unix.Catalog.GetString ("Output");
		this.notebook1.SetTabLabel (this.scrolledwindow1, this.label6);
		this.label6.ShowAll ();
		this.vpaned1.Add (this.notebook1);
		this.vbox1.Add (this.vpaned1);
		global::Gtk.Box.BoxChild w159 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.vpaned1]));
		w159.Position = 1;
		// Container child vbox1.Gtk.Box+BoxChild
		this.statusBar = new global::Gtk.Statusbar ();
		this.statusBar.Name = "statusBar";
		this.statusBar.Spacing = 6;
		this.statusBar.BorderWidth = ((uint)(1));
		// Container child statusBar.Gtk.Box+BoxChild
		this.label31 = new global::Gtk.Label ();
		this.label31.Name = "label31";
		this.label31.LabelProp = global::Mono.Unix.Catalog.GetString ("Generation Time (ms) : ");
		this.statusBar.Add (this.label31);
		global::Gtk.Box.BoxChild w160 = ((global::Gtk.Box.BoxChild)(this.statusBar [this.label31]));
		w160.Position = 1;
		w160.Expand = false;
		w160.Fill = false;
		// Container child statusBar.Gtk.Box+BoxChild
		this.elapsedGenTimeLabel = new global::Gtk.Label ();
		this.elapsedGenTimeLabel.Name = "elapsedGenTimeLabel";
		this.elapsedGenTimeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.statusBar.Add (this.elapsedGenTimeLabel);
		global::Gtk.Box.BoxChild w161 = ((global::Gtk.Box.BoxChild)(this.statusBar [this.elapsedGenTimeLabel]));
		w161.Position = 2;
		w161.Expand = false;
		w161.Fill = false;
		// Container child statusBar.Gtk.Box+BoxChild
		this.label17 = new global::Gtk.Label ();
		this.label17.Name = "label17";
		this.label17.LabelProp = global::Mono.Unix.Catalog.GetString ("Elapsed Time (ms) : ");
		this.statusBar.Add (this.label17);
		global::Gtk.Box.BoxChild w162 = ((global::Gtk.Box.BoxChild)(this.statusBar [this.label17]));
		w162.Position = 3;
		w162.Expand = false;
		w162.Fill = false;
		// Container child statusBar.Gtk.Box+BoxChild
		this.elapsedTimeLabel = new global::Gtk.Label ();
		this.elapsedTimeLabel.Name = "elapsedTimeLabel";
		this.elapsedTimeLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("0");
		this.statusBar.Add (this.elapsedTimeLabel);
		global::Gtk.Box.BoxChild w163 = ((global::Gtk.Box.BoxChild)(this.statusBar [this.elapsedTimeLabel]));
		w163.Position = 4;
		w163.Expand = false;
		w163.Fill = false;
		this.vbox1.Add (this.statusBar);
		global::Gtk.Box.BoxChild w164 = ((global::Gtk.Box.BoxChild)(this.vbox1 [this.statusBar]));
		w164.Position = 2;
		w164.Expand = false;
		w164.Fill = false;
		w164.Padding = ((uint)(1));
		this.Add (this.vbox1);
		if ((this.Child != null)) {
			this.Child.ShowAll ();
		}
		this.Show ();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler (this.OnDeleteEvent);
		this.quitAction.Activated += new global::System.EventHandler (this.MenuFileQuit);
		this.AboutAction.Activated += new global::System.EventHandler (this.MenuHelpAbout);
		this.openAction.Activated += new global::System.EventHandler (this.MenuFileOpen);
		this.ClearAction.Activated += new global::System.EventHandler (this.ClearOutputText);
		this.startButton.Clicked += new global::System.EventHandler (this.Start);
		this.stopButton.Clicked += new global::System.EventHandler (this.Stop);
		this.pauseButton.Clicked += new global::System.EventHandler (this.Pause);
		this.stepButton.Clicked += new global::System.EventHandler (this.Step);
		this.resumeButton.Clicked += new global::System.EventHandler (this.Resume);
		this.threadDelayHScale.ValueChanged += new global::System.EventHandler (this.ThreadDelay);
		this.reEvaluateCheckbutton.Toggled += new global::System.EventHandler (this.ReEvaluateAll);
		this.linearNormalisationCheckButton.Toggled += new global::System.EventHandler (this.LinearlyNormalised);
		this.evaluateInParallelCheckButton.Toggled += new global::System.EventHandler (this.EvaluateInParallel);
		this.fitnessProportionalRadioButton.Toggled += new global::System.EventHandler (this.FitnessProportionalRadioButton);
		this.stochasticUniversalRadioButton.Toggled += new global::System.EventHandler (this.StochasticUniversalRadioButton);
		this.tournamentRadioButton.Toggled += new global::System.EventHandler (this.TournamentRadioButtor);
		this.statisticsCheckButton.Toggled += new global::System.EventHandler (this.StatisticsEnable);
		this.distributionHScale.ValueChanged += new global::System.EventHandler (this.DiversityGraphScale);
		this.crossoverEnabledCheckButton.Toggled += new global::System.EventHandler (this.CrossoverEnabled);
		this.crossoverAllowDuplicatesCheckButton.Toggled += new global::System.EventHandler (this.CrossoverAllowDuplicates);
		this.crossoverProbabilityHScale.ValueChanged += new global::System.EventHandler (this.CrossoverProbability);
		this.crossoverTypeSingleRadioButton.Toggled += new global::System.EventHandler (this.CrossoverTypeSingle);
		this.crossoverTypeDoubleRadioButton.Toggled += new global::System.EventHandler (this.CrossoverTypeDouble);
		this.crossoverTypeDoubleOrderedRadioButton.Toggled += new global::System.EventHandler (this.CrossoverTypeDoubleOrdered);
		this.crossoverReplacementGenerational.Toggled += new global::System.EventHandler (this.CrossoverReplacementGeneric);
		this.crossoverReplacementDeleteLast.Toggled += new global::System.EventHandler (this.CrossoverReplacementDeleteLast);
		this.binaryMutateEnabledCheckButton.Toggled += new global::System.EventHandler (this.BinaryMutateEnabled);
		this.binaryMutateAllowDuplicatesCheckButton.Toggled += new global::System.EventHandler (this.BinaryMutateAllowDuplicates);
		this.binaryMutateProbabilityHScale.ValueChanged += new global::System.EventHandler (this.BinaryMutateProbability);
		this.eliteEnabledCheckButton.Toggled += new global::System.EventHandler (this.EliteEnabled);
		this.elitePercentageHScale.ValueChanged += new global::System.EventHandler (this.ElitePercentage);
		this.randomReplaceEnabledCheckButton.Toggled += new global::System.EventHandler (this.RandomReplaceEnabled);
		this.randomReplaceAllowDuplicatesCheckButton.Toggled += new global::System.EventHandler (this.RandomReplaceAllowDuplicates);
		this.randomReplacePercentageHScale.ValueChanged += new global::System.EventHandler (this.RandomReplacePercentage);
		this.swapMutateEnabledCheckButton.Toggled += new global::System.EventHandler (this.SwapMutateEnabled);
		this.swapMutateProbabilityHScale.ValueChanged += new global::System.EventHandler (this.SwapMutateProbability);
		this.memoryEnabledCheckButton.Toggled += new global::System.EventHandler (this.MemoryEnabled);
		this.memorySizeHScale.ValueChanged += new global::System.EventHandler (this.MemorySize);
		this.memoryUpdateHScale.ValueChanged += new global::System.EventHandler (this.MemoryUpdatePeriod);
	}
}
