// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GAF.Api {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HelpText {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HelpText() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("GAF.Api.HelpText", typeof(HelpText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CrossoverDescription {
            get {
                return ResourceManager.GetString("CrossoverDescription", resourceCulture);
            }
        }
        
        internal static string EliteDescription {
            get {
                return ResourceManager.GetString("EliteDescription", resourceCulture);
            }
        }
        
        internal static string BinaryMutateDescription {
            get {
                return ResourceManager.GetString("BinaryMutateDescription", resourceCulture);
            }
        }
        
        internal static string CopyDescription {
            get {
                return ResourceManager.GetString("CopyDescription", resourceCulture);
            }
        }
        
        internal static string RandomReplaceDescription {
            get {
                return ResourceManager.GetString("RandomReplaceDescription", resourceCulture);
            }
        }
        
        internal static string SwapMutateDescription {
            get {
                return ResourceManager.GetString("SwapMutateDescription", resourceCulture);
            }
        }
        
        internal static string MemoryDescription {
            get {
                return ResourceManager.GetString("MemoryDescription", resourceCulture);
            }
        }
        
        internal static string StatisticsDescription {
            get {
                return ResourceManager.GetString("StatisticsDescription", resourceCulture);
            }
        }
        
        internal static string SourceCodeDescription {
            get {
                return ResourceManager.GetString("SourceCodeDescription", resourceCulture);
            }
        }
        
        internal static string GenotypicViewDescription {
            get {
                return ResourceManager.GetString("GenotypicViewDescription", resourceCulture);
            }
        }
        
        internal static string Licence {
            get {
                return ResourceManager.GetString("Licence", resourceCulture);
            }
        }
    }
}
